package com.blissofgiving.dynamodbmodel;

import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "BENEFICIARY_MEDIA")
public class BeneficiaryMedia{

    @DynamoDBHashKey(attributeName = "BENEFICIARY_SYS_GUID")
    private String beneficiarySysGuid;

    @DynamoDBAttribute(attributeName = "MEDIA_SYS_GUID")
    private String mediaSysGuid;

    @DynamoDBIndexHashKey( globalSecondaryIndexName = "CREATED_USER_INDEX", attributeName = "CREATED_USER")
    private String createdUser;

    @DynamoDBAttribute(attributeName = "CREATED_DATE")
    private Date createdDate;

    @DynamoDBAttribute(attributeName = "LAST_UPDATE_USER")
    private String lastUpdateUser;

    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    @DynamoDBAttribute(attributeName = "LAST_UPDATE_DATE")
    private Date lastUpdateDate;

    public String getBeneficiarySysGuid() {
        return beneficiarySysGuid;
    }

    public void setBeneficiarySysGuid(String beneficiarySysGuid) {
        this.beneficiarySysGuid = beneficiarySysGuid;
    }

    public String getMediaSysGuid() {
        return mediaSysGuid;
    }

    public void setMediaSysGuid(String mediaSysGuid) {
        this.mediaSysGuid = mediaSysGuid;
    }

    public String getCreatedUser() {
        return createdUser;
    }

    public void setCreatedUser(String createdUser) {
        this.createdUser = createdUser;
    }

    public Date getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    public String getLastUpdateUser() {
        return lastUpdateUser;
    }

    public void setLastUpdateUser(String lastUpdateUser) {
        this.lastUpdateUser = lastUpdateUser;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
}
