package com.blissofgiving.dynamodbmodel;

import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "BENEFICIARY_TESTIMONIALS")
public class BeneficiaryTestimonials {
	@DynamoDBHashKey(attributeName = "TESTIMONIAL_SYS_GUID")
	private String testimonialSysGuid;
	@DynamoDBAttribute(attributeName = "FUNDRAISE_SYS_GUID")
	private String fundraiseSysGuid;
	@DynamoDBAttribute(attributeName = "BENEFICIARY_SYS_GUID")
	private String beneficiarySysGuid;
	@DynamoDBAttribute(attributeName = "TESTIMONIAL_LIKES")
	private Double testimonialLikes;
	@DynamoDBAttribute(attributeName = "TESTIMONIAL_DATA")
	private String testimonialData;
	@DynamoDBIndexHashKey(globalSecondaryIndexName = "CREATED_USER_INDEX", attributeName = "CREATED_USER")
	private String createdUser;
	@DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
	@DynamoDBAttribute(attributeName = "CREATED_DATE")
	private Date createdDate;
	@DynamoDBAttribute(attributeName = "LAST_UPDATE_USER")
	private String lastUpdateUser;
	@DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
	@DynamoDBAttribute(attributeName = "LAST_UPDATE_DATE")
	private Date lastUpdateDate;

	public String getTestimonialSysGuid() {
		return testimonialSysGuid;
	}

	public void setTestimonialSysGuid(String testimonialSysGuid) {
		this.testimonialSysGuid = testimonialSysGuid;
	}

	public String getFundraiseSysGuid() {
		return fundraiseSysGuid;
	}

	public void setFundraiseSysGuid(String fundraiseSysGuid) {
		this.fundraiseSysGuid = fundraiseSysGuid;
	}

	public String getBeneficiarySysGuid() {
		return beneficiarySysGuid;
	}

	public void setBeneficiarySysGuid(String beneficiarySysGuid) {
		this.beneficiarySysGuid = beneficiarySysGuid;
	}

	public Double getTestimonialLikes() {
		return testimonialLikes;
	}

	public void setTestimonialLikes(Double testimonialLikes) {
		this.testimonialLikes = testimonialLikes;
	}

	public String getTestimonialData() {
		return testimonialData;
	}

	public void setTestimonialData(String testimonialData) {
		this.testimonialData = testimonialData;
	}

	public String getCreatedUser() {
		return createdUser;
	}

	public void setCreatedUser(String createdUser) {
		this.createdUser = createdUser;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getLastUpdateUser() {
		return lastUpdateUser;
	}

	public void setLastUpdateUser(String lastUpdateUser) {
		this.lastUpdateUser = lastUpdateUser;
	}

	public Date getLastUpdateDate() {
		return lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}
}
