package com.blissofgiving.dynamodbmodel;

import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "BENEFICIARY_PAYMENT")
public class BeneficiaryPayment {

	@DynamoDBHashKey(attributeName = "BENEFICIARY_PAYMENT_SYS_GUID")
	private String beneficiaryDonationSysGuid;

	@DynamoDBIndexHashKey(globalSecondaryIndexName = "BENEFICIARY_SYS_GUID_INDEX", attributeName = "BENEFICIARY_SYS_GUID")
	private String beneficiarySysGUID;

	@DynamoDBAttribute(attributeName = "AMOUNT")
	private Long amount;

	@DynamoDBAttribute(attributeName = "CURRENCY")
	private String currency;

	@DynamoDBAttribute(attributeName = "DESCRIPTION")
	private String description;

	@DynamoDBAttribute(attributeName = "BILLING_DETAILS")
	private String billingDetails;

	@DynamoDBAttribute(attributeName = "INVOICE")
	private String invoice;

	@DynamoDBAttribute(attributeName = "RECEIPT_EMAIL")
	private String receiptEmail;

	@DynamoDBAttribute(attributeName = "LAST_UPDATE_USER")
	private String lastUpdateUser;

	@DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
	@DynamoDBAttribute(attributeName = "LAST_UPDATE_DATE")
	private Date lastUpdateDate;

	public String getBeneficiaryDonationSysGuid() {
		return beneficiaryDonationSysGuid;
	}

	public void setBeneficiaryDonationSysGuid(String beneficiaryDonationSysGuid) {
		this.beneficiaryDonationSysGuid = beneficiaryDonationSysGuid;
	}

	public String getBeneficiarySysGUID() {
		return beneficiarySysGUID;
	}

	public void setBeneficiarySysGUID(String beneficiarySysGUID) {
		this.beneficiarySysGUID = beneficiarySysGUID;
	}

	public Long getAmount() {
		return amount;
	}

	public void setAmount(Long amount) {
		this.amount = amount;
	}

	public String getCurrency() {
		return currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getBillingDetails() {
		return billingDetails;
	}

	public void setBillingDetails(String billingDetails) {
		this.billingDetails = billingDetails;
	}

	public String getInvoice() {
		return invoice;
	}

	public void setInvoice(String invoice) {
		this.invoice = invoice;
	}

	public String getReceiptEmail() {
		return receiptEmail;
	}

	public void setReceiptEmail(String receiptEmail) {
		this.receiptEmail = receiptEmail;
	}

	public String getLastUpdateUser() {
		return lastUpdateUser;
	}

	public void setLastUpdateUser(String lastUpdateUser) {
		this.lastUpdateUser = lastUpdateUser;
	}

	public Date getLastUpdateDate() {
		return lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}
}
