package com.blissofgiving.dynamodbmodel;

import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "FUNDRAISE_COMMENT")
public class FundraiseComment {

	@DynamoDBHashKey(attributeName = "FUNDRAISE_COMMENTS_SYS_GUID")
	private String fundRaiseCommentSysGuid;

	@DynamoDBIndexHashKey(globalSecondaryIndexName = "FUNDRAISE_SYS_GUID_INDEX", attributeName = "FUNDRAISE_SYS_GUID")
	private String fundraiseSysGuid;

	@DynamoDBAttribute(attributeName = "FUNDRAISE_COMMENT")
	private String fundraiseComment;

	@DynamoDBAttribute(attributeName = "CREATED_USER")
	private String createdUser;


	@DynamoDBAttribute(attributeName = "CREATED_DATE")
	private Date createdDate;

	@DynamoDBAttribute(attributeName = "LAST_UPDATE_USER")
	private String lastUpdateUser;

	@DynamoDBAttribute(attributeName = "LAST_UPDATE_DATE")
	@DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
	private Date lastUpdateDate;

	public String getFundRaiseCommentSysGuid() {
		return fundRaiseCommentSysGuid;
	}

	public void setFundRaiseCommentSysGuid(String fundRaiseCommentSysGuid) {
		this.fundRaiseCommentSysGuid = fundRaiseCommentSysGuid;
	}

	public String getFundraiseSysGuid() {
		return fundraiseSysGuid;
	}

	public void setFundraiseSysGuid(String fundraiseSysGuid) {
		this.fundraiseSysGuid = fundraiseSysGuid;
	}

	public String getFundraiseComment() {
		return fundraiseComment;
	}

	public void setFundraiseComment(String fundraiseComment) {
		this.fundraiseComment = fundraiseComment;
	}

	public String getCreatedUser() {
		return createdUser;
	}

	public void setCreatedUser(String createdUser) {
		this.createdUser = createdUser;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getLastUpdateUser() {
		return lastUpdateUser;
	}

	public void setLastUpdateUser(String lastUpdateUser) {
		this.lastUpdateUser = lastUpdateUser;
	}

	public Date getLastUpdateDate() {
		return lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}
}
