package com.blissofgiving.dynamodbmodel;

import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "FUNDRAISE_MEDIA")
public class FundraiseMedia {

	@DynamoDBIndexHashKey(globalSecondaryIndexName = "FUNDRAISE_SYS_INDEX",attributeName = "FUNDRAISE_SYS_GUID")
	private String fundraiseSysGuid;

	@DynamoDBHashKey(attributeName = "MEDIA_SYS_GUID")
	@DynamoDBAutoGeneratedKey
	private String mediaSysGuid;

	@DynamoDBAttribute(attributeName = "CREATED_USER")
	private String createdUser;

	@DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
	@DynamoDBAttribute(attributeName = "CREATED_DATE")
	private Date createdDate;

	@DynamoDBAttribute(attributeName = "LAST_UPDATE_USER")
	private String lastUpdateUser;

	@DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
	@DynamoDBAttribute(attributeName = "LAST_UPDATE_DATE")
	private Date lastUpdateDate;

	@DynamoDBAttribute(attributeName = "FUNDRAISE_MEDIA_LINK")
	private String mediaLink;

	public String getFundraiseSysGuid() {
		return fundraiseSysGuid;
	}

	public void setFundraiseSysGuid(String fundraiseSysGuid) {
		this.fundraiseSysGuid = fundraiseSysGuid;
	}

	public String getMediaSysGuid() {
		return mediaSysGuid;
	}

	public void setMediaSysGuid(String mediaSysGuid) {
		this.mediaSysGuid = mediaSysGuid;
	}

	public String getCreatedUser() {
		return createdUser;
	}

	public void setCreatedUser(String createdUser) {
		this.createdUser = createdUser;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getLastUpdateUser() {
		return lastUpdateUser;
	}

	public void setLastUpdateUser(String lastUpdateUser) {
		this.lastUpdateUser = lastUpdateUser;
	}

	public Date getLastUpdateDate() {
		return lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

	public String getMediaLink() {
		return mediaLink;
	}

	public void setMediaLink(String mediaLink) {
		this.mediaLink = mediaLink;
	}
}
