package com.blissofgiving.dynamodbmodel;

import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "FUNDRAISE")
public class Fundraise {

	//Primary Key
	//@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey(attributeName = "FUNDRAISE_SYS_GUID")
	private String fundraiseSysGUID;

	@DynamoDBAttribute(attributeName = "FUNDRAISE_TITLE")
	private String fundraiseTitle;

	@DynamoDBAttribute(attributeName = "FUNDRAISE_DESCRIPTION")
	private String fundraiseDescription;

	@DynamoDBAttribute(attributeName = "FUNDRAISE_TOTAL")
	private Double fundraiseTotal;

	@DynamoDBAttribute(attributeName = "FUNDRAISE_TYPE")
	private String fundraiseType;

	@DynamoDBAttribute(attributeName = "FUNDRAISE_STATUS")
	private Boolean fundraiseStatus;

	@DynamoDBAttribute(attributeName = "START_DATE")
	private Date startDate;

	@DynamoDBAttribute(attributeName = "END_DATE")
	private Date endDate;

	//Range Key
//	@DynamoDBRangeKey(attributeName = "CREATED_USER")
	@DynamoDBIndexHashKey( globalSecondaryIndexName = "CREATED_USER_INDEX", attributeName = "CREATED_USER")
	private String createdUser;

	@DynamoDBAttribute(attributeName = "CREATED_DATE")
	private Date createdDate;

	@DynamoDBAttribute(attributeName = "LAST_UPDATE_USER")
	private String lastUpdateUser;

	@DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
	@DynamoDBAttribute(attributeName = "LAST_UPDATE_DATE")
	private Date lastUpdateDate;

	public String getFundraiseSysGUID() {
		return fundraiseSysGUID;
	}

	public void setFundraiseSysGUID(String fundraiseSysGUID) {
		this.fundraiseSysGUID = fundraiseSysGUID;
	}

	public String getFundraiseTitle() {
		return fundraiseTitle;
	}

	public void setFundraiseTitle(String fundraiseTitle) {
		this.fundraiseTitle = fundraiseTitle;
	}

	public String getFundraiseDescription() {
		return fundraiseDescription;
	}

	public void setFundraiseDescription(String fundraiseDescription) {
		this.fundraiseDescription = fundraiseDescription;
	}

	public Double getFundraiseTotal() {
		return fundraiseTotal;
	}

	public void setFundraiseTotal(Double fundraiseTotal) {
		this.fundraiseTotal = fundraiseTotal;
	}

	public String getFundraiseType() {
		return fundraiseType;
	}

	public void setFundraiseType(String fundraiseType) {
		this.fundraiseType = fundraiseType;
	}

	public Boolean getFundraiseStatus() {
		return fundraiseStatus;
	}

	public void setFundraiseStatus(Boolean fundraiseStatus) {
		this.fundraiseStatus = fundraiseStatus;
	}

	public Date getStartDate() {
		return startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public String getCreatedUser() {
		return createdUser;
	}

	public void setCreatedUser(String createdUser) {
		this.createdUser = createdUser;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getLastUpdateUser() {
		return lastUpdateUser;
	}

	public void setLastUpdateUser(String lastUpdateUser) {
		this.lastUpdateUser = lastUpdateUser;
	}

	public Date getLastUpdateDate() {
		return lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}
}
